config/routes.rb
Rails.application.routes.draw do
  match "/admin" => redirect("/bolt")
  match "bolt/dashboard" => "bolt/dashboard#index"

  get "bolt/media/index"
  get "bolt/media/:id"  => "bolt/media#getfolderdatas", :as => "fetch_folder_data" 
  post "bolt/media/uploadFile"
  post "bolt/media/create_folder" => "bolt/media#create_folder", :as => "create_folder"  
  post "bolt/media/delete_folder" => "bolt/media#delete_folder", :as => "delete_folder"
  post "bolt/media/delete_file" => "bolt/media#delete_file", :as => "delete_file"
  get "/:cat_name/:id-:title" => "bolt/info#show", :as => :ambiguous_section, :defaults => {:id => nil, :cat_name => "Articles", :title => nil}
  get "/:id" => "bolt/info#show", :as => :page, :defaults => {:id => "Home", :cat => nil}
  root :to => "bolt/info#show"
  post "bolt/settings/:id" => "bolt/settings#update", :as => "update" 
  
  namespace :bolt do
		resources :banners
		resources :settings
    resources :page_sections
    resources :pages
    resources :articles_categories
    resources :user_statuses
    resources :statuses
    resources :accesses
    resources :categories
    resources :blogs
    resources :articles    
    resources :groups
    resources :users_groups
    resources :articles
    resources :media      

    resources :users do
      member do
        put :update_password, :reset_password
      end
    end
    
    resource :user_session
    resource :password_reset, :only => [:create, :edit, :update]
    
    match "/blank" => "bolt#blank"    
  end

   match ':controller(/:action(/:id(.:format)))'
end

app/models/article.rb
class Article < ActiveRecord::Base
  
  ######   association ###########
  
  validates :title, :presence => true
  validates :alias, :presence => true
  
  belongs_to :status
  belongs_to :access
  has_many :articles_categories
  has_many :categories, :through => :articles_categories, :dependent => :destroy
  accepts_nested_attributes_for :articles_categories, :reject_if => proc { |attributes| attributes['category_id'].blank? || attributes['category_id'].to_i == 0}, :allow_destroy => true
     
 ######### for FEATURED ########
 
 NO =0
 YES =1
 FEATURED_TYPES ={
   NO =>"No",
   YES =>"Yes"
   
 }   
end

app/models/bolt.rb
module Bolt
 
end

app/controllers/bolt/accesses_controller.rb
module Bolt
  class AccessesController < Bolt::BoltController
  
    ## optional filters for defining usage according to Bolt::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @bolt_page_title = 'Accesses'
  		@accesses = Access.paginate :page => params[:page]
    end
  
    def show
      @bolt_page_title = 'View access'
      @access = Access.find params[:id]
    end
 
    def new
      @bolt_page_title = 'Add a new access'
    	@access = Access.new
    end

    def create
      @access = Access.new params[:access]
    
      if @access.save
        flash[:notice] = 'Access created'
        redirect_to bolt_accesses_path
      else
        flash.now[:warning] = 'Name can not be blank'
        render :action => :new
      end
    end
  
    def update
      @bolt_page_title = 'Update access'
      
      @access = Access.find params[:id]
    
      if @access.update_attributes params[:access]
        flash[:notice] = 'Access has been updated'
        redirect_to bolt_accesses_path
      else
        flash.now[:warning] = 'Name can not be blank'
        render :action => :show
      end
    end
 
    def destroy
      @access = Access.find params[:id]

      @access.destroy
      flash[:notice] = 'Access has been deleted'
      redirect_to bolt_accesses_path
    end
   def destroy_multiple
      ids= params[:id]
      idarr=ids.split(',')
      idarr.each do |del|
        @blog = Access.find(del)
        @blog.destroy
      end
      respond_to do |format|
        format.html { redirect_to :back  }
        # format.json { head :ok }
      end
   end
  
  
  end
end

app/controllers/bolt/articles_categories_controller.rb
module Bolt
  class ArticlesCategoriesController < Bolt::BoltController
  
    ## optional filters for defining usage according to Bolt::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @bolt_page_title = 'Articles categories'
  		@articles_categories = ArticlesCategory.paginate :page => params[:page]
    end
                                    
    def show
      @bolt_page_title = 'View articles category'
      @articles_category = ArticlesCategory.find params[:id]
    end
 
    def new
      @bolt_page_title = 'Add a new articles category'
    	@articles_category = ArticlesCategory.new
    end

    def create
      @articles_category = ArticlesCategory.new params[:articles_category]
    
      if @articles_category.save
        flash[:notice] = 'Articles category created'
        redirect_to bolt_articles_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new articles category'
        render :action => :new
      end
    end
  
    def update
      @bolt_page_title = 'Update articles category'
      
      @articles_category = ArticlesCategory.find params[:id]
    
      if @articles_category.update_attributes params[:articles_category]
        flash[:notice] = 'Articles category has been updated'
        redirect_to bolt_articles_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to update this articles category'
        render :action => :show
      end
    end
 
    def destroy
      @articles_category = ArticlesCategory.find params[:id]

      @articles_category.destroy
      flash[:notice] = 'Articles category has been deleted'
      redirect_to bolt_articles_categories_path
    end
   def destroy_multiple
      ids= params[:id]
      idarr=ids.split(',')
      idarr.each do |del|
        @blog = ArticlesCategory.find(del)
        @blog.destroy
      end
      respond_to do |format|
        format.html { redirect_to :back  }
        # format.json { head :ok }
      end
   end
  
  
  end
end

app/controllers/bolt/articles_controller.rb
module Bolt
  class ArticlesController < Bolt::BoltController
  
    ## optional filters for defining usage according to Bolt::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index

     sortcolumn=(params[:sort]==nil) ? ' ' : params[:sort] 
      @bolt_articles = Article.find(:all)
      @bolt_page_title = 'Articles'
      @articles = Article.paginate(:page => params[:page], :order => sortcolumn)
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @bolt_articles }
      end
    end
  
    def show 
      @bolt_article = Article.find(params[:id])
      @bolt_page_title = 'View article'
      @article = Article.find params[:id]
      @categories =Category.all
      @statuses = Status.all
      @accesses  = Access.all                
      @u_categories = @bolt_article
         
    end
 
    def new
      @bolt_page_title = 'Add a new article'
      @article = Article.new
      @categories =Category.all
      @statuses = Status.all
      @accesses  = Access.all
       respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @bolt_articles }
      end 
    end

    def create
      @article = Article.new params[:article]
    
      if @article.save
        flash[:notice] = 'Article created'
        redirect_to bolt_articles_path
      else
        @categories =Category.all
        @statuses = Status.all
        @accesses  = Access.all                
        flash.now[:warning] = 'There were problems when trying to create a new article'
        render :action => :new
      end
    end
  
    def update
      @bolt_page_title = 'Update article'
      
      @article = Article.find params[:id]
    
      if @article.update_attributes params[:article]
        flash[:notice] = 'Article has been updated'
        redirect_to bolt_articles_path
      else
        flash.now[:warning] = 'There were problems when trying to update this article'
        render :action => :show
      end
    end
 
    def destroy
      @article = Article.find params[:id]

      @article.destroy
      flash[:notice] = 'Article has been deleted'
      redirect_to bolt_articles_path
    end

    def destroy_multiple
    ids= params[:id]
    idarr=ids.split(',')
    idarr.each do |del|
      @article = Article.find(del)
      @article.destroy
    end
    respond_to do |format|
      format.html { redirect_to :back  }
      # format.json { head :ok }
    end
    
  end
  
  end
end

app/controllers/bolt/banners_controller.rb
module Bolt
  class BannersController < Bolt::BoltController
  
    ## optional filters for defining usage according to Bolt::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @bolt_page_title = 'Banners'
  		@banners = Banner.paginate :page => params[:page]
    end
  
    def show
      @bolt_page_title = 'View banner'
      @banner = Banner.find params[:id]
    end
 
    def new
      @bolt_page_title = 'Add a new banner'
    	@banner = Banner.new
    end

    def create
      @banner = Banner.new params[:banner]
    
      if @banner.save
        flash[:notice] = 'Banner created'
        redirect_to bolt_banners_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new banner'
        render :action => :new
      end
    end
  
    def update
      @bolt_page_title = 'Update banner'
      
      @banner = Banner.find params[:id]
    
      if @banner.update_attributes params[:banner]
        flash[:notice] = 'Banner has been updated'
        redirect_to bolt_banners_path
      else
        flash.now[:warning] = 'There were problems when trying to update this banner'
        render :action => :show
      end
    end
 
    def destroy
      @banner = Banner.find params[:id]

      @banner.destroy
      flash[:notice] = 'Banner has been deleted'
      redirect_to bolt_banners_path
    end
  
  end
end

app/controllers/bolt/blogs_controller.rb
module Bolt
  class BlogsController < Bolt::BoltController
  
    ## optional filters for defining usage according to Bolt::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index

    sortcolumn=(params[:sort]==nil)? ' ' : params[:sort]  
    @bolt_blogs = Blog.find(:all)
    @bolt_page_title = 'Blogs'
    @blogs = Blog.paginate(:page => params[:page], :order => sortcolumn)
     
    end
  
    def show
      @bolt_blog = Blog.find(params[:id])
      @bolt_page_title = 'View blog'
      @blog = Blog.find params[:id]
    end

   def new
      @bolt_page_title = 'Add a new blog'
    	@blog = Blog.new
    end

    def create
      @blog = Blog.new params[:blog]
    
      if @blog.save
        flash[:notice] = 'Blog created'
        redirect_to bolt_blogs_path
      else
        flash.now[:warning] = 'Title can not be blank!'
        render :action => :new
      end
    end
  
    def update
      @bolt_page_title = 'Update blog'
      
      @blog = Blog.find params[:id]
    
      if @blog.update_attributes params[:blog]
        flash[:notice] = 'Blog has been updated'
        redirect_to bolt_blogs_path
      else
        flash.now[:warning] =  'Title can not be blank!'
        render :action => :show
      end
    end
 
    def destroy
      @blog = Blog.find params[:id]

      @blog.destroy
      flash[:notice] = 'Blog has been deleted'
      redirect_to bolt_blogs_path
    end
      def destroy
      @blog = Blog.find params[:id]

      @blog.destroy
      flash[:notice] = 'Blog has been deleted'
      redirect_to :back
    end
    def destroy_multiple
      ids= params[:id]
      idarr=ids.split(',')
      idarr.each do |del|
        @blog = Blog.find(del)
        @blog.destroy
      end
      respond_to do |format|
        format.html { redirect_to :back  }
        # format.json { head :ok }
      end
   end
  
  end
end

app/controllers/bolt/categories_controller.rb
module Bolt
  class CategoriesController < Bolt::BoltController
  
    ## optional filters for defining usage according to Bolt::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index               
      @bolt_page_title = 'Categories'
  		@categories = Category.paginate :page => params[:page]
    end
  
    def show
      @bolt_page_title = 'View category'
      @category = Category.find params[:id]
    end
 
    def new
      @bolt_page_title = 'Add a new category'
    	@category = Category.new
    end

    def create
      @category = Category.new params[:category]
    
      if @category.save
        flash[:notice] = 'Category created'
        redirect_to bolt_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new category'
        render :action => :new
      end
    end
  
    def update
      @bolt_page_title = 'Update category'
      
      @category = Category.find params[:id]
    
      if @category.update_attributes params[:category]
        flash[:notice] = 'Category has been updated'
        redirect_to bolt_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to update this category'
        render :action => :show
      end
    end
 
    def destroy
      @category = Category.find params[:id]

      @category.destroy
      flash[:notice] = 'Category has been deleted'
      redirect_to bolt_categories_path
    end
    
    def destroy_multiple
     ids= params[:id]
     idarr=ids.split(',')
     idarr.each do |del|
      @category = Category.find(del)
      @category.destroy
     end
    respond_to do |format|
      format.html { redirect_to :back  }
      # format.json { head :ok }
    end
    
  end
  
  end
end

app/controllers/bolt/dashboard_controller.rb
# Scaffolding generated by Backbone v.3.1.11

module Bolt
  class DashboardController < Bolt::BoltController
  
   
    def index
    end

  end
end

app/controllers/bolt/groups_controller.rb
module Bolt
class GroupsController < ApplicationController
  # GET /bolt/groups
  # GET /bolt/groups.json
  layout "bolt_main"
  def index
   sortcolumn=(params[:sort]==nil)? 'name' : params[:sort]  
   @groups = Group.find(:all, :order => sortcolumn)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @groups }
    end
  end

  # GET /bolt/groups/1
  # GET /bolt/groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @group }
    end
  end

  # GET /bolt/groups/new
  # GET /bolt/groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @group }
    end
  end

  # GET /bolt/groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /bolt/groups
  # POST /bolt/groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to :action => "index", :notice => 'Group was successfully created.' }
        format.json { render :json => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.json { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bolt/groups/1
  # PUT /bolt/groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to :action=>"index", :notice => 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bolt/groups/1
  # DELETE /bolt/groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end
     
    def destroy_multiple
     ids= params[:id]
     idarr=ids.split(',')
     idarr.each do |del|
      @group = Group.find(del)
      @group.destroy
    end
    respond_to do |format|
      format.html { redirect_to :back  }
      # format.json { head :ok }
    end
   end
   
end
end

app/controllers/bolt/info_controller.rb
module Bolt
  class InfoController < Bolt::BoltController
    layout "default_site"
    def show   
       @site_settings=Setting.find(1)   
      @top_menu = Page.parent_menu
      if(!params[:cat_name].nil?)
        if(!params[:cat_name].match(/article/i).nil?)
          if(!params[:id].nil?)
            @article = Article.find(params[:id].to_i)
          end
        else
          @articles = Article.published
        end      
      else
        @categories = Category.all        
        if(params[:id].nil? || !params[:id].match(/index|home/i).nil?)
          @page = Page.find_by_title("Home")        
        else      
          @page = Page.find_by_title(deformat_url_id(params[:id]))
        end
       
      end
    end
  end
end 

app/views/bolt/articles/_form.html.erb
<style type="text/css">
.center
{
margin:auto;
width:-10%;

}
p.ag
{

width:40%;
}
.scroll {
	border:1px solid silver;
width: 200px; 
height: 100px;
padding-left: 10px;
padding-right: 5px; 
overflow: auto;
}
</style>
<div class="tab">
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table id='usr'>
    <tr>
    <td width="150"><%= f.label :title %></td>
    <td><%= f.text_field :title%></td></tr>
    	



<tr>
  <td width="150">  <%= f.label :alias %></td>
    <td><%= f.text_field :alias %>
</td>
</tr>

   <tr>
    <td width="150"><%= f.label :status %></td>
    <td><select name="article[status_id]">
    <% @statuses.each do |status|%>
   	<option value="<%= status.id %>">
   		<%= status.name %>
   	</option>
      
  
    <%end%> 
    </select> </td></tr>
  
  <tr>
    <td width="150">
    <%= f.label :access %></td>
    <td><select name="article[access_id]">
    <% @accesses.each do |access|%>
   	<option value="<%= access.id %>">
   		<%= access.name %>
   	</option>
      
    <%end%>
    </select></td></tr>
 
<tr><td width="150">
    <%= f.label :featured %></td>
    <td><%= f.select :featured, Article::FEATURED_TYPES.map{|key, value| [value, key]} %></td>
    </tr>
       	 <tr><td width="150">Assining Categories</td><td><div class="center">


<% if(action_name == "new") %>
<%   @categories.each do |ug| %>
	 <%= f.fields_for :articles_categories, @article.articles_categories.build do |g_fields| %>
     <%= g_fields.check_box :category_id, {:checked => false}, ug.id %><%= ug.name %>&nbsp;
     <% end %>
<%   end 
   end
%>
<%  if(action_name != "new") %>
      <%= f.fields_for :articles_categories do |g_fields| %>
      <%= g_fields.hidden_field :category_id %>
      <%= g_fields.check_box :_destroy, {:checked => g_fields.object.persisted?}, 0, 1 %><%= g_fields.object.category.name %>
      <% end %>
      <% @categories.each do |ug| %>
      <% if(!@article.categories.include?(ug)) %>
        <%= f.fields_for :articles_categories, @article.articles_categories.build do |g_fields| %>
        <%= g_fields.check_box :category_id, {:checked => false}, ug.id %><%= ug.name %>&nbsp;
<%       end
         end
        end
    end
%>
</div>
    </td>
   
    </tr>
  <tr><td width="150">
    <%= f.label :body %></td>
    <td><%= f.text_area :body,:cols => "100"%>
    </td>
  </tr>


 </table>

app/views/bolt/articles/_table.html.erb
<table id="container" bgcolor="#F0F0F0" align="left" width="100%">
  <tr><thead>
    <th align="left"><input type="checkbox" id="chkunchk"  onclick="select_all()"/></th>
    <th align="left"><a href = "/bolt/articles?sort=title">Title</th>
    <th align="left"><a href = "/bolt/articles?sort=alias">Alias</th>
    <th align="left">Category</th>
    <th align="left">Status</th>
    <th align="left">Access</th>
    <th align="left">Featured</th>
       </thead> 
  </tr>

<% @articles.each do |article| %>
  <tr>
  <td style="px"><input class='selall'  type='checkbox' id='chk_<%=article.id%>'  name ='checkbox' onclick="test()"  value='<%=article.id %>'></td>

    <td><%= article.title %></td>
    <td><%= article.alias %></td>
   <td><% article.categories.each do |g| %>
     <%= g.name.titleize %>,
     <% end %>
   </td>
    <td><%= article.status.nil? ? "" : article.status.name %></td>
    <td><%= article.access.nil? ? "" : article.access.name%></td>
    <td><%= Article::FEATURED_TYPES[article.featured] %></td>
    
  </tr>
<% end %>
</table>

app/views/bolt/articles/_title.html.erb
<table  width="100%">
<td width="6%"><a  href="<%= bolt_articles_path %>" ><b>Articles</b></a></td>
<td width="7%"><a  href="<%= bolt_categories_path %>" ><B>Categories</b></a></td>
<td width="7%"><a  href="<%= bolt_accesses_path %>" ><B>Accesses</b></a></td>
<td><a  href="<%= bolt_statuses_path %>" ><B>Statuses</b></a>

</td>
</table>
<br/><br/>

app/views/bolt/articles/index.html.erb
<script type="text/javascript" src="/bolt/javascripts/javascript_functions.js" ></script>
<table  width="100%"><td width="1%"><%= image_tag("/bolt/images/article.png",:size => '40x40') %></td><td><font color="blue" size="5">Article Manager:Articles</td>

<td><p style="text-align:right;">new&nbsp;&nbsp;edit&nbsp;&nbsp;delete</p>
<p style="text-align:right;"><a  href="<%= new_bolt_article_path %>" ><%= image_tag("/bolt/images/new.png") %></a>&nbsp;&nbsp;
<a id="edit"  href="javascript:void(0)"  onclick="edit_rec('/bolt/articles/');"><%= image_tag("/bolt/images/edit.png",:size=>"20x20") %></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a id="delete" href="javascript:void(0)" onclick="delete_rec('/bolt/articles/destroy_multiple/');"><%= image_tag("/bolt/images/delete.png") %></a>
&nbsp;&nbsp;</p></td></table><br/><br>
<%= render :partial=>"title"%>
<br/><br/>

<style type="text/css">
table { border: 1px solid lightGrey }

#container {
  
    width: 100%; }
td { border: 3px solid white; }
th { border: 3px solid white; } 

table#container tr:hover td {
  background-color: cornsilk ;
}             
  
</style>
<h2>Articles</h2>

<%= render :partial => 'bolt/articles/table', :locals => { :articles => @articles } %>

<%= will_paginate @articles %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{bolt_show_icon "add"}Add a new article".html_safe, new_bolt_article_path %></li>
<% end %>

app/views/bolt/articles/new.html.erb
<h2>Add a new article</h2>
<p align="right">Cancel</p><p align="right"><a  href="/bolt/articles" ><%= image_tag("/bolt/images/cancel.png") %></a>&nbsp;&nbsp;&nbsp;</p>
<%= form_for @article, :url => bolt_articles_path do |f| %>

<%= render :partial => 'bolt/articles/form', :locals => { :f => f } %>

<p class="submits">
  <%= link_to 'Cancel', bolt_articles_path, :class => 'cancel' %> or
  <%= f.submit "Add new article", :class => "update" %>
</p>

<% end %>

<%= content_for :sidebar do %>
<li><%= link_to "#{bolt_show_icon "table"}Back to list".html_safe, bolt_articles_path %></li>
<% end %>

app/views/bolt/articles/show.html.erb
<h2>View article</h2>

<%= form_for @article, :url => bolt_article_path(@article) do |f| %>

<%= render :partial => 'bolt/articles/form', :locals => { :f => f } %>

<p class="submits">
  <%= link_to 'Cancel', bolt_articles_path, :class => 'cancel' %> or
  <%= f.submit "Save changes", :class => "update" %>
</p>

<% end %>

<%= content_for :sidebar do %>
<li><%= link_to "#{bolt_show_icon "table"}Back to list".html_safe, bolt_articles_path %></li>
<% end %>