config/routes.rb
Rails.application.routes.draw do
  match "/admin" => redirect("/bolt")
  match "bolt/dashboard" => "bolt/dashboard#index"

  get "bolt/media/index"
  get "bolt/media/:id"  => "bolt/media#getfolderdatas", :as => "fetch_folder_data" 
  post "bolt/media/uploadFile"
  post "bolt/media/create_folder" => "bolt/media#create_folder", :as => "create_folder"  
  post "bolt/media/delete_folder" => "bolt/media#delete_folder", :as => "delete_folder"
  post "bolt/media/delete_file" => "bolt/media#delete_file", :as => "delete_file"
  get "/:cat_name/:id-:title" => "bolt/info#show", :as => :ambiguous_section, :defaults => {:id => nil, :cat_name => "Articles", :title => nil}
  get "/:id" => "bolt/info#show", :as => :page, :defaults => {:id => "Home", :cat => nil}
  root :to => "bolt/info#show"
  post "bolt/settings/:id" => "bolt/settings#update", :as => "update" 
  
  namespace :bolt do
		resources :banners
		resources :settings
    resources :page_sections
    resources :pages
    resources :articles_categories
    resources :user_statuses
    resources :statuses
    resources :accesses
    resources :categories
    resources :blogs
    resources :articles    
    resources :groups
    resources :users_groups
    resources :articles
    resources :media      

    resources :users do
      member do
        put :update_password, :reset_password
      end
    end
    
    resource :user_session
    resource :password_reset, :only => [:create, :edit, :update]
    
    match "/blank" => "bolt#blank"    
  end

   match ':controller(/:action(/:id(.:format)))'
end

app/models/bolt.rb
module Bolt
 
end

app/models/bolt/user_session.rb
module Bolt
  class UserSession < ::Authlogic::Session::Base
    include ActiveModel::Conversion 
    def persisted? 
      false 
    end
  end
end

app/controllers/bolt/accesses_controller.rb
module Bolt
  class AccessesController < Bolt::BoltController
  
    ## optional filters for defining usage according to Bolt::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @bolt_page_title = 'Accesses'
  		@accesses = Access.paginate :page => params[:page]
    end
  
    def show
      @bolt_page_title = 'View access'
      @access = Access.find params[:id]
    end
 
    def new
      @bolt_page_title = 'Add a new access'
    	@access = Access.new
    end

    def create
      @access = Access.new params[:access]
    
      if @access.save
        flash[:notice] = 'Access created'
        redirect_to bolt_accesses_path
      else
        flash.now[:warning] = 'Name can not be blank'
        render :action => :new
      end
    end
  
    def update
      @bolt_page_title = 'Update access'
      
      @access = Access.find params[:id]
    
      if @access.update_attributes params[:access]
        flash[:notice] = 'Access has been updated'
        redirect_to bolt_accesses_path
      else
        flash.now[:warning] = 'Name can not be blank'
        render :action => :show
      end
    end
 
    def destroy
      @access = Access.find params[:id]

      @access.destroy
      flash[:notice] = 'Access has been deleted'
      redirect_to bolt_accesses_path
    end
   def destroy_multiple
      ids= params[:id]
      idarr=ids.split(',')
      idarr.each do |del|
        @blog = Access.find(del)
        @blog.destroy
      end
      respond_to do |format|
        format.html { redirect_to :back  }
        # format.json { head :ok }
      end
   end
  
  
  end
end

app/controllers/bolt/articles_categories_controller.rb
module Bolt
  class ArticlesCategoriesController < Bolt::BoltController
  
    ## optional filters for defining usage according to Bolt::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @bolt_page_title = 'Articles categories'
  		@articles_categories = ArticlesCategory.paginate :page => params[:page]
    end
                                    
    def show
      @bolt_page_title = 'View articles category'
      @articles_category = ArticlesCategory.find params[:id]
    end
 
    def new
      @bolt_page_title = 'Add a new articles category'
    	@articles_category = ArticlesCategory.new
    end

    def create
      @articles_category = ArticlesCategory.new params[:articles_category]
    
      if @articles_category.save
        flash[:notice] = 'Articles category created'
        redirect_to bolt_articles_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new articles category'
        render :action => :new
      end
    end
  
    def update
      @bolt_page_title = 'Update articles category'
      
      @articles_category = ArticlesCategory.find params[:id]
    
      if @articles_category.update_attributes params[:articles_category]
        flash[:notice] = 'Articles category has been updated'
        redirect_to bolt_articles_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to update this articles category'
        render :action => :show
      end
    end
 
    def destroy
      @articles_category = ArticlesCategory.find params[:id]

      @articles_category.destroy
      flash[:notice] = 'Articles category has been deleted'
      redirect_to bolt_articles_categories_path
    end
   def destroy_multiple
      ids= params[:id]
      idarr=ids.split(',')
      idarr.each do |del|
        @blog = ArticlesCategory.find(del)
        @blog.destroy
      end
      respond_to do |format|
        format.html { redirect_to :back  }
        # format.json { head :ok }
      end
   end
  
  
  end
end

app/controllers/bolt/articles_controller.rb
module Bolt
  class ArticlesController < Bolt::BoltController
  
    ## optional filters for defining usage according to Bolt::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index

     sortcolumn=(params[:sort]==nil) ? ' ' : params[:sort] 
      @bolt_articles = Article.find(:all)
      @bolt_page_title = 'Articles'
      @articles = Article.paginate(:page => params[:page], :order => sortcolumn)
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @bolt_articles }
      end
    end
  
    def show 
      @bolt_article = Article.find(params[:id])
      @bolt_page_title = 'View article'
      @article = Article.find params[:id]
      @categories =Category.all
      @statuses = Status.all
      @accesses  = Access.all                
      @u_categories = @bolt_article
         
    end
 
    def new
      @bolt_page_title = 'Add a new article'
      @article = Article.new
      @categories =Category.all
      @statuses = Status.all
      @accesses  = Access.all
       respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @bolt_articles }
      end 
    end

    def create
      @article = Article.new params[:article]
    
      if @article.save
        flash[:notice] = 'Article created'
        redirect_to bolt_articles_path
      else
        @categories =Category.all
        @statuses = Status.all
        @accesses  = Access.all                
        flash.now[:warning] = 'There were problems when trying to create a new article'
        render :action => :new
      end
    end
  
    def update
      @bolt_page_title = 'Update article'
      
      @article = Article.find params[:id]
    
      if @article.update_attributes params[:article]
        flash[:notice] = 'Article has been updated'
        redirect_to bolt_articles_path
      else
        flash.now[:warning] = 'There were problems when trying to update this article'
        render :action => :show
      end
    end
 
    def destroy
      @article = Article.find params[:id]

      @article.destroy
      flash[:notice] = 'Article has been deleted'
      redirect_to bolt_articles_path
    end

    def destroy_multiple
    ids= params[:id]
    idarr=ids.split(',')
    idarr.each do |del|
      @article = Article.find(del)
      @article.destroy
    end
    respond_to do |format|
      format.html { redirect_to :back  }
      # format.json { head :ok }
    end
    
  end
  
  end
end

app/controllers/bolt/banners_controller.rb
module Bolt
  class BannersController < Bolt::BoltController
  
    ## optional filters for defining usage according to Bolt::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @bolt_page_title = 'Banners'
  		@banners = Banner.paginate :page => params[:page]
    end
  
    def show
      @bolt_page_title = 'View banner'
      @banner = Banner.find params[:id]
    end
 
    def new
      @bolt_page_title = 'Add a new banner'
    	@banner = Banner.new
    end

    def create
      @banner = Banner.new params[:banner]
    
      if @banner.save
        flash[:notice] = 'Banner created'
        redirect_to bolt_banners_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new banner'
        render :action => :new
      end
    end
  
    def update
      @bolt_page_title = 'Update banner'
      
      @banner = Banner.find params[:id]
    
      if @banner.update_attributes params[:banner]
        flash[:notice] = 'Banner has been updated'
        redirect_to bolt_banners_path
      else
        flash.now[:warning] = 'There were problems when trying to update this banner'
        render :action => :show
      end
    end
 
    def destroy
      @banner = Banner.find params[:id]

      @banner.destroy
      flash[:notice] = 'Banner has been deleted'
      redirect_to bolt_banners_path
    end
  
  end
end

app/controllers/bolt/blogs_controller.rb
module Bolt
  class BlogsController < Bolt::BoltController
  
    ## optional filters for defining usage according to Bolt::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index

    sortcolumn=(params[:sort]==nil)? ' ' : params[:sort]  
    @bolt_blogs = Blog.find(:all)
    @bolt_page_title = 'Blogs'
    @blogs = Blog.paginate(:page => params[:page], :order => sortcolumn)
     
    end
  
    def show
      @bolt_blog = Blog.find(params[:id])
      @bolt_page_title = 'View blog'
      @blog = Blog.find params[:id]
    end

   def new
      @bolt_page_title = 'Add a new blog'
    	@blog = Blog.new
    end

    def create
      @blog = Blog.new params[:blog]
    
      if @blog.save
        flash[:notice] = 'Blog created'
        redirect_to bolt_blogs_path
      else
        flash.now[:warning] = 'Title can not be blank!'
        render :action => :new
      end
    end
  
    def update
      @bolt_page_title = 'Update blog'
      
      @blog = Blog.find params[:id]
    
      if @blog.update_attributes params[:blog]
        flash[:notice] = 'Blog has been updated'
        redirect_to bolt_blogs_path
      else
        flash.now[:warning] =  'Title can not be blank!'
        render :action => :show
      end
    end
 
    def destroy
      @blog = Blog.find params[:id]

      @blog.destroy
      flash[:notice] = 'Blog has been deleted'
      redirect_to bolt_blogs_path
    end
      def destroy
      @blog = Blog.find params[:id]

      @blog.destroy
      flash[:notice] = 'Blog has been deleted'
      redirect_to :back
    end
    def destroy_multiple
      ids= params[:id]
      idarr=ids.split(',')
      idarr.each do |del|
        @blog = Blog.find(del)
        @blog.destroy
      end
      respond_to do |format|
        format.html { redirect_to :back  }
        # format.json { head :ok }
      end
   end
  
  end
end

app/controllers/bolt/categories_controller.rb
module Bolt
  class CategoriesController < Bolt::BoltController
  
    ## optional filters for defining usage according to Bolt::Users access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index               
      @bolt_page_title = 'Categories'
  		@categories = Category.paginate :page => params[:page]
    end
  
    def show
      @bolt_page_title = 'View category'
      @category = Category.find params[:id]
    end
 
    def new
      @bolt_page_title = 'Add a new category'
    	@category = Category.new
    end

    def create
      @category = Category.new params[:category]
    
      if @category.save
        flash[:notice] = 'Category created'
        redirect_to bolt_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new category'
        render :action => :new
      end
    end
  
    def update
      @bolt_page_title = 'Update category'
      
      @category = Category.find params[:id]
    
      if @category.update_attributes params[:category]
        flash[:notice] = 'Category has been updated'
        redirect_to bolt_categories_path
      else
        flash.now[:warning] = 'There were problems when trying to update this category'
        render :action => :show
      end
    end
 
    def destroy
      @category = Category.find params[:id]

      @category.destroy
      flash[:notice] = 'Category has been deleted'
      redirect_to bolt_categories_path
    end
    
    def destroy_multiple
     ids= params[:id]
     idarr=ids.split(',')
     idarr.each do |del|
      @category = Category.find(del)
      @category.destroy
     end
    respond_to do |format|
      format.html { redirect_to :back  }
      # format.json { head :ok }
    end
    
  end
  
  end
end

app/controllers/bolt/dashboard_controller.rb
# Scaffolding generated by Backbone v.3.1.11

module Bolt
  class DashboardController < Bolt::BoltController
  
   
    def index
    end

  end
end

app/controllers/bolt/groups_controller.rb
module Bolt
class GroupsController < ApplicationController
  # GET /bolt/groups
  # GET /bolt/groups.json
  layout "bolt_main"
  def index
   sortcolumn=(params[:sort]==nil)? 'name' : params[:sort]  
   @groups = Group.find(:all, :order => sortcolumn)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @groups }
    end
  end

  # GET /bolt/groups/1
  # GET /bolt/groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @group }
    end
  end

  # GET /bolt/groups/new
  # GET /bolt/groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @group }
    end
  end

  # GET /bolt/groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /bolt/groups
  # POST /bolt/groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to :action => "index", :notice => 'Group was successfully created.' }
        format.json { render :json => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.json { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bolt/groups/1
  # PUT /bolt/groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to :action=>"index", :notice => 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bolt/groups/1
  # DELETE /bolt/groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end
     
    def destroy_multiple
     ids= params[:id]
     idarr=ids.split(',')
     idarr.each do |del|
      @group = Group.find(del)
      @group.destroy
    end
    respond_to do |format|
      format.html { redirect_to :back  }
      # format.json { head :ok }
    end
   end
   
end
end

app/controllers/bolt/info_controller.rb
module Bolt
  class InfoController < Bolt::BoltController
    layout "default_site"
    def show   
       @site_settings=Setting.find(1)   
      @top_menu = Page.parent_menu
      if(!params[:cat_name].nil?)
        if(!params[:cat_name].match(/article/i).nil?)
          if(!params[:id].nil?)
            @article = Article.find(params[:id].to_i)
          end
        else
          @articles = Article.published
        end      
      else
        @categories = Category.all        
        if(params[:id].nil? || !params[:id].match(/index|home/i).nil?)
          @page = Page.find_by_title("Home")        
        else      
          @page = Page.find_by_title(deformat_url_id(params[:id]))
        end
       
      end
    end
  end
end 

app/views/bolt/users_bk/_form.html.erb
<fieldset class="biswa">
<h2>Account Details</h2>

<%= form_for(@bolt_user) do |f| %>
  <% if @bolt_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bolt_user.errors.count, "error") %> prohibited this bolt_user from being saved:</h2>

      <ul>
      <% @bolt_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :login_name %><br/>
    <%= f.text_field :login_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :confirm_password %><br/>
    <%= f.text_field :confirm_password %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :registration_date %><br/>
    <%= f.date_select :registration_date %>
  </div>
  <div class="field">
    <%= f.label :last_visit_date %><br/>
    <%= f.date_select :last_visit_date %>
  </div>
  <div class="field">
    <%= f.label :receive_system_emails %>
   
     
    <%= f.radio_button :receive_system_emails, 'no', :checked => true %> NO
    <%= f.radio_button :receive_system_emails, 'yes' %> yes
  </div>
  <div class="field">
    <%= f.label :Block_this_user %>
   
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.radio_button :Block_this_user, 'no', :checked => true %>NO
    &nbsp;<%= f.radio_button :Block_this_user, 'yes' %> yes
  </div>
    <div class="field">
    <%= f.label :id%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= @bolt_user.id %>
 </fieldset><br/>

<fieldset class="biswa1">
<h2>Assigned User Groups</h2>

 <div class="field">
    
   <%  @bolt_user_group.each do |user| %>
       <input type="checkbox" id="<%=user.id%>" value="<%=user.id%>"/><%=user.name%> <br/>
   <%  end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bolt/users_bk/edit.html.erb
<p align="right">Cancel</p><p align="right"><a  href="/bolt/articles" ><%= image_tag("cancel.png") %></a>&nbsp;&nbsp;&nbsp;</p>

<h1>Editing bolt_user</h1>

<%= render 'form' %>

app/views/bolt/users_bk/index.html.erb
<h1>Listing bolt_users</h1>
<p style="text-align:right;">new&nbsp;&nbsp;edit&nbsp;&nbsp;delete</p>
<p style="text-align:right;"><a  href="/bolt/users/new" ><%= image_tag("new.png") %></a>&nbsp;&nbsp;
<a id="edit" href=""><%= image_tag("edit.png",:size=>"20x20") %></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a id="delete" href="#"><%= image_tag("delete.png") %></a>
&nbsp;&nbsp;</p><br/><br/>
<style type="text/css">
table { border: 1px solid black; }

#container {
  
    width: 100%; }
td { border: 3px solid white; }
th { border: 3px solid white; }

</style>
<script type="text/javascript">


function delete_it(id)
{
                        
 document.getElementById('delete').href="/bolt/users/destroy/"+id;
 document.getElementById('edit').href="/bolt/users/edit/"+id;
 
}
</script>
<table id="container" bgcolor="Cornsilk" align="left">
  <tr>
    <td><input type="checkbox"></td>
  
    <td><font color="blue">Name</td>
    <td><font color="blue">Login name</td>
    <td><font color="blue">User Groups</td>
    <td><font color="blue">Email</td>
    <td><font color="blue">Last visit date</td>
    <td><font color="blue">Registration date</td>
    <td><font color="blue">ID</td>  	
  </tr>

<% @bolt_users.each do |bolt_user| %>
  <tr>
    <td><input type="checkbox" onclick="delete_it('<%= bolt_user.id %>')"  ></td>
    <td><%= bolt_user.name %></td>
    <td><%= bolt_user.login_name %></td>
    
     <td><%= bolt_user.email %></td>
    <td><%= bolt_user.last_visit_date %></td>
    <td><%= bolt_user.registration_date %></td>
   <td><%= bolt_user.id %></td>
 </tr>
<% end %>

</table>

<br />

app/views/bolt/users_bk/new.html.erb
<p align="right">Cancel</p><p align="right"><a  href="/bolt/users" ><%= image_tag("cancel.png") %></a>&nbsp;&nbsp;&nbsp;</p>

<h1>User Manager: Add New User</h1>

<%= render 'form' %>

app/views/bolt/users_bk/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bolt_user.name %>
</p>

<p>
  <b>Login name:</b>
  <%= @bolt_user.login_name %>
</p>

<p>
  <b>Password:</b>
  <%= @bolt_user.password %>
</p>

<p>
  <b>Confirm password:</b>
  <%= @bolt_user.confirm_password %>
</p>

<p>
  <b>Email:</b>
  <%= @bolt_user.email %>
</p>

<p>
  <b>Registration date:</b>
  <%= @bolt_user.registration_date %>
</p>

<p>
  <b>Last visit date:</b>
  <%= @bolt_user.last_visit_date %>
</p>

<p>
  <b>Receive system emails:</b>
  <%= @bolt_user.receive_system_emails %>
</p>

<p>
  <b>Block this user:</b>
  <%= @bolt_user.Block_this_user %>
</p>

<p>
  <b>Public:</b>
  <%= @bolt_user.public %>
</p>

<p>
  <b>Manager:</b>
  <%= @bolt_user.manager %>
</p>

<p>
  <b>Administrator:</b>
  <%= @bolt_user.administrator %>
</p>

<p>
  <b>Registered:</b>
  <%= @bolt_user.registered %>
</p>

<p>
  <b>Author:</b>
  <%= @bolt_user.author %>
</p>

<p>
  <b>Editor:</b>
  <%= @bolt_user.editor %>
</p>

<p>
  <b>Publisher:</b>
  <%= @bolt_user.publisher %>
</p>

<p>
  <b>Shop suppliers:</b>
  <%= @bolt_user.shop_suppliers %>
</p>

<p>
  <b>Customer group:</b>
  <%= @bolt_user.customer_group %>
</p>

<p>
  <b>Super users:</b>
  <%= @bolt_user.super_users %>
</p>


<%= link_to 'Edit', edit_bolt_user_path(@bolt_user) %> |
<%= link_to 'Back', bolt_users_path %>